### ISSUE TITLE
Show loading state of asset list (or hide latency)

### ISSUE THREAD

**Issue by rjw57** [uisautomation/iar-frontend#102]
The asset list updates when the new list is fetched from the server but this is typically 100-200ms after the request. This can be clicking a column heading or clicking a department in the sidebar.

Providing some feedback of asset list fetching is desirable both from a UI consistency PoV (so the list reflects the other UI elements' state) and also from a latency hiding PoV.

As an example: on re-load, the current asset list could fade out, a loading indicator be shown and the new list fade in. In typical timings the loading indicator may not even be shown resulting in the old asset list fading away and the new one appearing.

A more "material" way would to be to have the old asset list animate off-screen and the new one animate on-screen.

The loading transition should be designed and implemented to reduce perceived lag between clicking a UI element and the effect being shown.

**Comment by abrahammartin** [comment]
This was done as part of another story and is already deployed. Loading helper now appears in the top of the screen, every time someone clicks a section of the UI.
