### ISSUE TITLE
Navigation logic is inconsistent

### ISSUE THREAD

**Issue by rjw57** [uisautomation/iar-frontend#104]
As a user, if I

1. Open a new tab,
2. Go to the entry list,
3. Open an entry to edit,
4. Save it, thereby going back to the entry list, and
5. Press the "back button"

I would expect to go back to the entry but instead I go to the "new tab" page for by browser. This is because the "go back" button in the app, shouldn't have the semantics of the "back button" in the browser: I'm not going back in history, I am progressing *forward* by navigating to the asset list.

We need to revisit this since cancelling navigation via the prompt added to address #62 can further complicate this history stack.

**Comment by abrahammartin** [comment]
Cancel button also produces this problem.

**Comment by rjw57** [comment]
Do we consider it release critical?

**Comment by abrahammartin** [comment]
Don't think we need, but it's going to the next sprint as it's quite relevant.
