### ISSUE TITLE
"Cannot update during an existing state transition" warning in console

### ISSUE THREAD

**Issue by msb** [uisautomation/iar-frontend#117]
index.js:2178 Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

**Comment by rjw57** [comment]
Poking in the console, this appears to originate from FetchSelf.js:17.

**Comment by rjw57** [comment]
Closed by be01870c
