### ISSUE TITLE
Upgrade npm dependencies

### ISSUE THREAD

**Issue by rjw57** [uisautomation/iar-frontend#168]
PR #167 has been reverted because it broke IE11 support when actually deployed. The branch with reverted commits now functions correctly on IE11 when deployed.

The changes from #167 need re-working to get the same effect but to keep IE11 support.

**Comment by abrahammartin** [comment]
We can now deprecate IE11 support including wording to tell users to contact their local COs or UIS Desktop support if they have a managed PC and they don't have alternative browser to IE11.
