### ISSUE TITLE
Refactor create/edit form to use redux

### ISSUE THREAD

**Issue by rjw57** [uisautomation/iar-frontend#26]
Refactor existing create/edit form to use redux-api-middleware.

**Comment by abrahammartin** [comment]
need justification

**Comment by rjw57** [comment]
The API auth token is only directly visible to components who are aware of the redux state. A minimal implementation of this PR would therefore wire up just enough redux to get access to the token.

However this will not detect token timeout and automatically re-login. Token expiry is a global issue and is best solved in the API middleware rather than being duplicated in every component. If we accept that, then we need to make the form component API middleware aware. At that point, having wired up the redux state and the API middleware, we might as well just make the fetch calls via the middleware instead of hanging on to our own calls.

**Comment by abrahammartin** [comment]
closed by #9
