### ISSUE TITLE
Do we want to use BrowserRouter or HashRouter?

### ISSUE THREAD

**Issue by rjw57** [uisautomation/iar-frontend#31]
If we have the glorious vision of deploying this application as an S3 bucket, we need to deal with the fact that the bucket doesn't know how to deal with URLs like https://our-app/asset/xxx-yyy-zzz. It will return a 404. If we use HashRouter then the URLs become https://our-app/#asset/xxx-yyy-zzz which can be served from a single bucket.

**Comment by abrahammartin** [comment]
We are not using buckets, so this is not necessary anymore
