### ISSUE TITLE
Cancelling an asset edit form with unsaved changes should give a warning

### ISSUE THREAD

**Issue by joeadams04** [uisautomation/iar-frontend#62]
If you change at least one field in an asset, then attempt to navigate away (could be pressing the cancel button, navigating to a table or help page in the sidebar, pressing sign-out etc.) a warning dialog should appear warning you will lose unsaved changes.

**Comment by rjw57** [comment]
Blocked on #103 being merged.

**Comment by rjw57** [comment]
Blocked on #103 being merged because of the saveDraft() modifications there. Current implementation is at https://github.com/rjw57/iar-frontend/tree/issue-62-confirm-navigate-away-edit
