### ISSUE TITLE
When POST-ing or PUT-ing asset record, clear hidden fields

### ISSUE THREAD

**Issue by joeadams04** [uisautomation/iar-frontend#64]
When editing an asset:

Setting Personal Data to `true` enables all pd fields below, such as data subject and data category. Multiple choices can be made in these selection fields, which update the current asset state. If a user then decides to set Personal Data to `false`, all the pd fields that were previously enabled should cleared and reset to `null`.

Unlikely this will happen much, as you'd think the user would be confident there is personal data if they start filling out the questions underneath. However, we need to make sure it's impossible they can return a value in all the pd fields while pd = false.

**Comment by abrahammartin** [comment]
We agreed that the front end will not reset the data, but only hide it (scroll/hide) in case the user makes a mistakes / tries the other option and then ends up with an empty form. This data won't be sent though, when submitting the form.

**Comment by rjw57** [comment]
New asset form behaviour implements this hide/show mechanic. We still submit the private data fields, however.

**Comment by rjw57** [comment]
We've broadened this to other fields such as storage which are hidden dependent on other fields.
