### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/iar-frontend#7]
iar-frontend needs styling to look like the design done by Joe: https://projects.invisionapp.com/share/XUFAFXWZ8#/screens/272962556

- [ ] Header
- [ ] Sidebar
- [ ] Asset list
- [ ] Asset form
- [ ] Global branding

**Comment by rjw57** [comment]
We'll break these into separate issues to be sized.

**Comment by rjw57** [comment]
All dependent issues are closed
